// Mocks generated by Mockito 5.1.0 from annotations
// in ditonton/test/presentation/bloc/tvseries/popular/series_popular_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i6;
import 'package:ditonton/common/failure.dart' as _i8;
import 'package:ditonton/domain/entities/tvseries.dart' as _i9;
import 'package:ditonton/domain/repositories/tvseries_repository.dart' as _i5;
import 'package:ditonton/domain/usecases/get_popular_tvseries.dart' as _i2;
import 'package:ditonton/presentation/bloc/tvseries/tvseries_popular/series_popular_bloc.dart'
    as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetPopularTv_0 extends _i1.Fake implements _i2.GetPopularTv {}

class _FakeSeriesPopularState_1 extends _i1.Fake
    implements _i3.SeriesPopularState {}

class _FakeStreamSubscription_2<T> extends _i1.Fake
    implements _i4.StreamSubscription<T> {}

class _FakeTvSeriesRepository_3 extends _i1.Fake
    implements _i5.TvSeriesRepository {}

class _FakeEither_4<L, R> extends _i1.Fake implements _i6.Either<L, R> {}

/// A class which mocks [SeriesPopularBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeriesPopularBloc extends _i1.Mock implements _i3.SeriesPopularBloc {
  MockSeriesPopularBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetPopularTv get getPopularTv =>
      (super.noSuchMethod(Invocation.getter(#getPopularTv),
          returnValue: _FakeGetPopularTv_0()) as _i2.GetPopularTv);
  @override
  _i3.SeriesPopularState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeSeriesPopularState_1()) as _i3.SeriesPopularState);
  @override
  _i4.Stream<_i3.SeriesPopularState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i3.SeriesPopularState>.empty())
          as _i4.Stream<_i3.SeriesPopularState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i3.SeriesPopularEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i3.SeriesPopularEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i7.Transition<_i3.SeriesPopularEvent, _i3.SeriesPopularState>>
      transformEvents(
              _i4.Stream<_i3.SeriesPopularEvent>? events,
              _i7.TransitionFunction<_i3.SeriesPopularEvent, _i3.SeriesPopularState>?
                  transitionFn) =>
          (super.noSuchMethod(
                  Invocation.method(#transformEvents, [events, transitionFn]),
                  returnValue:
                      Stream<_i7.Transition<_i3.SeriesPopularEvent, _i3.SeriesPopularState>>.empty())
              as _i4.Stream<
                  _i7.Transition<_i3.SeriesPopularEvent, _i3.SeriesPopularState>>);
  @override
  void emit(_i3.SeriesPopularState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i3.SeriesPopularEvent>(
          _i7.EventHandler<E, _i3.SeriesPopularState>? handler,
          {_i7.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i3.SeriesPopularState> mapEventToState(
          _i3.SeriesPopularEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i3.SeriesPopularState>.empty())
          as _i4.Stream<_i3.SeriesPopularState>);
  @override
  void onTransition(
          _i7.Transition<_i3.SeriesPopularEvent, _i3.SeriesPopularState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i7.Transition<_i3.SeriesPopularEvent, _i3.SeriesPopularState>>
      transformTransitions(
              _i4.Stream<_i7.Transition<_i3.SeriesPopularEvent, _i3.SeriesPopularState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue:
                      Stream<_i7.Transition<_i3.SeriesPopularEvent, _i3.SeriesPopularState>>.empty())
              as _i4.Stream<
                  _i7.Transition<_i3.SeriesPopularEvent, _i3.SeriesPopularState>>);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.StreamSubscription<_i3.SeriesPopularState> listen(
          void Function(_i3.SeriesPopularState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_2<_i3.SeriesPopularState>())
          as _i4.StreamSubscription<_i3.SeriesPopularState>);
  @override
  void onChange(_i7.Change<_i3.SeriesPopularState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [GetPopularTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTv extends _i1.Mock implements _i2.GetPopularTv {
  MockGetPopularTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvSeriesRepository_3()) as _i5.TvSeriesRepository);
  @override
  _i4.Future<_i6.Either<_i8.Failure, List<_i9.TvSeries>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i6.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                      _FakeEither_4<_i8.Failure, List<_i9.TvSeries>>()))
          as _i4.Future<_i6.Either<_i8.Failure, List<_i9.TvSeries>>>);
}
